services:
  - type: web
    name: distle
    env: node
    plan: free
    buildCommand: "npm run install:all && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: ./distle.db
